# Generated by Django 5.1.1 on 2024-11-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=155, null=True)),
                ('email', models.CharField(blank=True, max_length=155, null=True)),
                ('password', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
    ]
