# Generated by Django 5.1.1 on 2024-11-28 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_userprofile_email_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.IntegerField()),
                ('checkin', models.DateField(default=django.utils.timezone.now)),
                ('checkout', models.DateField()),
            ],
        ),
    ]
