# Generated by Django 5.1.1 on 2024-11-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.CharField(choices=[('family', 'Family'), ('2_person', '2 Person'), ('group', 'Group')], max_length=10),
        ),
    ]
