# Generated by Django 5.1.1 on 2024-11-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_booking_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='House',
        ),
    ]
