# Generated by Django 4.2.7 on 2024-11-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_hotel_remove_house_checkin_remove_house_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1566073771259-6a8506099945', max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
